language: node_js
node_js:
  - '10.16.2'
services:
  - docker
script:
  - set -e

  # - echo 'Checking for missing change logs...' && echo -en 'travis_fold:start:change\\r'
  # - git fetch origin master:refs/remotes/origin/master -a
  # - node common/scripts/install-run-rush.js change -v
  # - echo -en 'travis_fold:end:change\\r'

  # - echo 'Installing...' && echo -en 'travis_fold:start:install\\r'
  # - node common/scripts/install-run-rush.js install
  # - echo -en 'travis_fold:end:install\\r'

  # - echo 'Building...' && echo -en 'travis_fold:start:build\\r'
  # - node common/scripts/install-run-rush.js rebuild --verbose
  # - echo -en 'travis_fold:end:build\\r'
  
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
  - docker pull wbern/rush-example:$TRAVIS_BRANCH
  - export CONTAINER_ID=$(docker run -d wbern/rush-example:$TRAVIS_BRANCH /bin/sh -c "sh ./docker-scripts/build.sh")
  - docker commit $CONTAINER_ID wbern/rush-example:$TRAVIS_BRANCH
  # - docker build -t wbern/rush-example:$TRAVIS_BRANCH .
  - docker push wbern/rush-example:$TRAVIS_BRANCH